// S&P 500 constituents — committed fallback for the nightly snapshot.
// The live path fetches the full ~503-name list fresh from FMP (/stable/sp-500);
// this file is only the resilience fallback used if that fetch fails, so it
// carries the curated leadership seed. Regenerate from FMP for a fuller offline
// fallback. Fields: tk, name, sector (FMP taxonomy), industry (FMP subSector).
export const SP500 = [
  { tk: "AAPL", name: "Apple", sector: "Technology", industry: "Consumer Electronics" },
  { tk: "ABBV", name: "AbbVie", sector: "Healthcare", industry: "Drug -Pharma" },
  { tk: "ABNB", name: "Airbnb", sector: "Consumer Cyclical", industry: "Travel -Leisure" },
  { tk: "ADBE", name: "Adobe", sector: "Technology", industry: "Software -Application" },
  { tk: "ADI", name: "Analog Devices", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "AEM", name: "Agnico Eagle Mines", sector: "Basic Materials", industry: "Mining -Gold/Silver" },
  { tk: "AFRM", name: "Affirm", sector: "Financial Services", industry: "Software -Infrastructure" },
  { tk: "AMD", name: "Advanced Micro Devices", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "AMGN", name: "Amgen", sector: "Healthcare", industry: "Drug -Biotech" },
  { tk: "AMZN", name: "Amazon", sector: "Consumer Cyclical", industry: "Internet -Retail" },
  { tk: "ANET", name: "Arista Networks", sector: "Technology", industry: "Elec -Networking" },
  { tk: "APP", name: "AppLovin", sector: "Technology", industry: "Software -Application" },
  { tk: "ARM", name: "Arm Holdings", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "ASML", name: "ASML Holding", sector: "Technology", industry: "Elec -Semiconductor Equip" },
  { tk: "AVGO", name: "Broadcom", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "AXON", name: "Axon Enterprise", sector: "Industrials", industry: "Aerospace -Defense" },
  { tk: "AXP", name: "American Express", sector: "Financial Services", industry: "Credit Services" },
  { tk: "BA", name: "Boeing", sector: "Industrials", industry: "Aerospace -Defense" },
  { tk: "BAC", name: "Bank of America", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "BKNG", name: "Booking Holdings", sector: "Consumer Cyclical", industry: "Travel -Leisure" },
  { tk: "BLK", name: "BlackRock", sector: "Financial Services", industry: "Asset Management" },
  { tk: "BSX", name: "Boston Scientific", sector: "Healthcare", industry: "Medical -Systems" },
  { tk: "C", name: "Citigroup", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "CAT", name: "Caterpillar", sector: "Industrials", industry: "Machinery -Const/Mining" },
  { tk: "CEG", name: "Constellation Energy", sector: "Utilities", industry: "Utility -Electric Power" },
  { tk: "CMG", name: "Chipotle", sector: "Consumer Cyclical", industry: "Retail -Restaurants" },
  { tk: "COIN", name: "Coinbase Global", sector: "Financial Services", industry: "Capital Markets" },
  { tk: "COP", name: "ConocoPhillips", sector: "Energy", industry: "Oil -E&P" },
  { tk: "COST", name: "Costco Wholesale", sector: "Consumer Defensive", industry: "Retail -Discount" },
  { tk: "CRDO", name: "Credo Technology", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "CRM", name: "Salesforce", sector: "Technology", industry: "Software -Application" },
  { tk: "CRWD", name: "CrowdStrike", sector: "Technology", industry: "Software -Security" },
  { tk: "CVX", name: "Chevron", sector: "Energy", industry: "Oil -Integrated" },
  { tk: "DASH", name: "DoorDash", sector: "Consumer Cyclical", industry: "Internet -Retail" },
  { tk: "DDOG", name: "Datadog", sector: "Technology", industry: "Software -Application" },
  { tk: "DELL", name: "Dell Technologies", sector: "Technology", industry: "Computer -Hardware" },
  { tk: "DKNG", name: "DraftKings", sector: "Consumer Cyclical", industry: "Gambling -Online" },
  { tk: "ETN", name: "Eaton", sector: "Industrials", industry: "Elec -Power/Thermal" },
  { tk: "FCX", name: "Freeport-McMoRan", sector: "Basic Materials", industry: "Mining -Copper" },
  { tk: "FDX", name: "FedEx", sector: "Industrials", industry: "Transport -Logistics" },
  { tk: "FTNT", name: "Fortinet", sector: "Technology", industry: "Software -Security" },
  { tk: "GD", name: "General Dynamics", sector: "Industrials", industry: "Aerospace -Defense" },
  { tk: "GEV", name: "GE Vernova", sector: "Industrials", industry: "Energy -Power" },
  { tk: "GOOGL", name: "Alphabet", sector: "Communication Services", industry: "Internet -Content" },
  { tk: "GS", name: "Goldman Sachs", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "HON", name: "Honeywell", sector: "Industrials", industry: "Diversified -Industrial" },
  { tk: "HOOD", name: "Robinhood Markets", sector: "Financial Services", industry: "Capital Markets" },
  { tk: "ICE", name: "Intercontinental Exchange", sector: "Financial Services", industry: "Capital Markets" },
  { tk: "INTC", name: "Intel", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "INTU", name: "Intuit", sector: "Technology", industry: "Software -Application" },
  { tk: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", industry: "Medical -Systems" },
  { tk: "JPM", name: "JPMorgan Chase", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "KGC", name: "Kinross Gold", sector: "Basic Materials", industry: "Mining -Gold/Silver" },
  { tk: "KLAC", name: "KLA Corp", sector: "Technology", industry: "Elec -Semiconductor Equip" },
  { tk: "LIN", name: "Linde", sector: "Basic Materials", industry: "Chemicals -Specialty" },
  { tk: "LLY", name: "Eli Lilly", sector: "Healthcare", industry: "Drug -Pharma" },
  { tk: "LMT", name: "Lockheed Martin", sector: "Industrials", industry: "Aerospace -Defense" },
  { tk: "LRCX", name: "Lam Research", sector: "Technology", industry: "Elec -Semiconductor Equip" },
  { tk: "LULU", name: "Lululemon", sector: "Consumer Cyclical", industry: "Apparel -Clothing" },
  { tk: "MA", name: "Mastercard", sector: "Financial Services", industry: "Credit Services" },
  { tk: "MCD", name: "McDonald's", sector: "Consumer Cyclical", industry: "Retail -Restaurants" },
  { tk: "MELI", name: "MercadoLibre", sector: "Consumer Cyclical", industry: "Internet -Retail" },
  { tk: "META", name: "Meta Platforms", sector: "Technology", industry: "Internet -Content" },
  { tk: "MRK", name: "Merck", sector: "Healthcare", industry: "Drug -Pharma" },
  { tk: "MRVL", name: "Marvell Technology", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "MS", name: "Morgan Stanley", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "MSFT", name: "Microsoft", sector: "Technology", industry: "Software -Infrastructure" },
  { tk: "MU", name: "Micron Technology", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "NEM", name: "Newmont", sector: "Basic Materials", industry: "Mining -Gold/Silver" },
  { tk: "NET", name: "Cloudflare", sector: "Technology", industry: "Software -Infrastructure" },
  { tk: "NFLX", name: "Netflix", sector: "Communication Services", industry: "Media -Streaming" },
  { tk: "NKE", name: "Nike", sector: "Consumer Cyclical", industry: "Apparel -Shoes" },
  { tk: "NOW", name: "ServiceNow", sector: "Technology", industry: "Software -Application" },
  { tk: "NU", name: "Nu Holdings", sector: "Financial Services", industry: "Banks -Foreign" },
  { tk: "NVDA", name: "NVIDIA", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "NXPI", name: "NXP Semiconductors", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "OKTA", name: "Okta", sector: "Technology", industry: "Software -Security" },
  { tk: "ON", name: "ON Semiconductor", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "ORCL", name: "Oracle", sector: "Technology", industry: "Software -Infrastructure" },
  { tk: "PANW", name: "Palo Alto Networks", sector: "Technology", industry: "Software -Security" },
  { tk: "PLTR", name: "Palantir", sector: "Technology", industry: "Software -Database" },
  { tk: "PYPL", name: "PayPal", sector: "Financial Services", industry: "Software -Infrastructure" },
  { tk: "QCOM", name: "Qualcomm", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "RBLX", name: "Roblox", sector: "Communication Services", industry: "Software -Gaming" },
  { tk: "REGN", name: "Regeneron", sector: "Healthcare", industry: "Drug -Biotech" },
  { tk: "SBUX", name: "Starbucks", sector: "Consumer Cyclical", industry: "Retail -Restaurants" },
  { tk: "SCHW", name: "Charles Schwab", sector: "Financial Services", industry: "Capital Markets" },
  { tk: "SHOP", name: "Shopify", sector: "Technology", industry: "Internet -Retail" },
  { tk: "SLB", name: "Schlumberger", sector: "Energy", industry: "Oil -Services" },
  { tk: "SMCI", name: "Super Micro Computer", sector: "Technology", industry: "Computer -Hardware" },
  { tk: "SNOW", name: "Snowflake", sector: "Technology", industry: "Software -Database" },
  { tk: "SPGI", name: "S&P Global", sector: "Financial Services", industry: "Capital Markets" },
  { tk: "SPOT", name: "Spotify", sector: "Communication Services", industry: "Media -Streaming" },
  { tk: "SQ", name: "Block", sector: "Financial Services", industry: "Software -Infrastructure" },
  { tk: "SYK", name: "Stryker", sector: "Healthcare", industry: "Medical -Systems" },
  { tk: "TMO", name: "Thermo Fisher", sector: "Healthcare", industry: "Medical -Products" },
  { tk: "TSLA", name: "Tesla", sector: "Consumer Cyclical", industry: "Auto -Manufacturers" },
  { tk: "TSM", name: "Taiwan Semiconductor", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "TXN", name: "Texas Instruments", sector: "Technology", industry: "Elec -Semiconductor" },
  { tk: "UBER", name: "Uber Technologies", sector: "Technology", industry: "Software -Application" },
  { tk: "UNH", name: "UnitedHealth", sector: "Healthcare", industry: "Medical -Managed Care" },
  { tk: "UNP", name: "Union Pacific", sector: "Industrials", industry: "Transport -Rail" },
  { tk: "V", name: "Visa", sector: "Financial Services", industry: "Credit Services" },
  { tk: "VRT", name: "Vertiv Holdings", sector: "Industrials", industry: "Elec -Power/Thermal" },
  { tk: "VRTX", name: "Vertex Pharma", sector: "Healthcare", industry: "Drug -Biotech" },
  { tk: "VST", name: "Vistra", sector: "Utilities", industry: "Utility -Electric Power" },
  { tk: "WDAY", name: "Workday", sector: "Technology", industry: "Software -Application" },
  { tk: "WFC", name: "Wells Fargo", sector: "Financial Services", industry: "Banks -Money Center" },
  { tk: "XOM", name: "Exxon Mobil", sector: "Energy", industry: "Oil -Integrated" },
  { tk: "ZS", name: "Zscaler", sector: "Technology", industry: "Software -Security" },
];
