// S&P 500 constituents — committed fallback for the nightly snapshot.
// The live path may refresh this from FMP; this committed list guarantees the
// full universe even when FMP is unavailable at runtime (prices still come from
// Yahoo). Regenerate occasionally as the index changes.
// Fields: tk, name, sector (FMP taxonomy), industry (FMP subSector).
export const SP500 = [
  { tk: "A", name: "Agilent Technologies", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "AAPL", name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics" },
  { tk: "ABBV", name: "AbbVie", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "ABNB", name: "Airbnb", sector: "Consumer Cyclical", industry: "Travel Services" },
  { tk: "ABT", name: "Abbott Laboratories", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "ACGL", name: "Arch Capital Group", sector: "Financial Services", industry: "Insurance - Diversified" },
  { tk: "ACN", name: "Accenture", sector: "Technology", industry: "Information Technology Services" },
  { tk: "ADBE", name: "Adobe Inc.", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "ADI", name: "Analog Devices", sector: "Technology", industry: "Semiconductors" },
  { tk: "ADM", name: "Archer Daniels Midland", sector: "Consumer Defensive", industry: "Agricultural Farm Products" },
  { tk: "ADP", name: "Automatic Data Processing", sector: "Industrials", industry: "Staffing & Employment Services" },
  { tk: "ADSK", name: "Autodesk", sector: "Technology", industry: "Software - Application" },
  { tk: "AEE", name: "Ameren", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "AEP", name: "American Electric Power", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "AES", name: "AES Corporation", sector: "Utilities", industry: "Diversified Utilities" },
  { tk: "AFL", name: "Aflac", sector: "Financial Services", industry: "Insurance - Life" },
  { tk: "AIG", name: "American International Group", sector: "Financial Services", industry: "Insurance - Diversified" },
  { tk: "AIZ", name: "Assurant", sector: "Financial Services", industry: "Insurance - Specialty" },
  { tk: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "AKAM", name: "Akamai Technologies", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "ALB", name: "Albemarle Corporation", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "ALGN", name: "Align Technology", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "ALL", name: "Allstate", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "ALLE", name: "Allegion", sector: "Industrials", industry: "Security & Protection Services" },
  { tk: "AMAT", name: "Applied Materials", sector: "Technology", industry: "Semiconductors" },
  { tk: "AMCR", name: "Amcor", sector: "Consumer Cyclical", industry: "Packaging & Containers" },
  { tk: "AMD", name: "Advanced Micro Devices", sector: "Technology", industry: "Semiconductors" },
  { tk: "AME", name: "Ametek", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "AMGN", name: "Amgen", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "AMP", name: "Ameriprise Financial", sector: "Financial Services", industry: "Asset Management" },
  { tk: "AMT", name: "American Tower", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "AMZN", name: "Amazon", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "ANET", name: "Arista Networks", sector: "Technology", industry: "Computer Hardware" },
  { tk: "AON", name: "Aon", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "AOS", name: "A. O. Smith", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "APA", name: "APA Corporation", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "APD", name: "Air Products", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "APH", name: "Amphenol", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "APO", name: "Apollo Global Management", sector: "Financial Services", industry: "Asset Management - Global" },
  { tk: "APP", name: "AppLovin Corporation", sector: "Technology", industry: "Software - Application" },
  { tk: "APTV", name: "Aptiv", sector: "Consumer Cyclical", industry: "Auto - Parts" },
  { tk: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate", industry: "REIT - Office" },
  { tk: "ARES", name: "Ares Management Corporation", sector: "Financial Services", industry: "Asset Management" },
  { tk: "ATO", name: "Atmos Energy", sector: "Utilities", industry: "Regulated Gas" },
  { tk: "AVB", name: "AvalonBay Communities", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "AVGO", name: "Broadcom", sector: "Technology", industry: "Semiconductors" },
  { tk: "AVY", name: "Avery Dennison", sector: "Industrials", industry: "Business Equipment & Supplies" },
  { tk: "AWK", name: "American Water Works", sector: "Utilities", industry: "Regulated Water" },
  { tk: "AXON", name: "Axon Enterprise", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "AXP", name: "American Express", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "AZO", name: "AutoZone", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "BA", name: "Boeing", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "BAC", name: "Bank of America", sector: "Financial Services", industry: "Banks - Diversified" },
  { tk: "BALL", name: "Ball Corporation", sector: "Consumer Cyclical", industry: "Packaging & Containers" },
  { tk: "BAX", name: "Baxter International", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "BBY", name: "Best Buy", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "BDX", name: "Becton Dickinson", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "BEN", name: "Franklin Resources", sector: "Financial Services", industry: "Asset Management" },
  { tk: "BF-B", name: "Brown–Forman", sector: "Consumer Defensive", industry: "Beverages - Wineries & Distilleries" },
  { tk: "BG", name: "Bunge Global", sector: "Consumer Defensive", industry: "Agricultural Farm Products" },
  { tk: "BIIB", name: "Biogen", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "BKNG", name: "Booking Holdings", sector: "Consumer Cyclical", industry: "Travel Services" },
  { tk: "BKR", name: "Baker Hughes", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { tk: "BLDR", name: "Builders FirstSource", sector: "Industrials", industry: "Construction" },
  { tk: "BLK", name: "BlackRock", sector: "Financial Services", industry: "Asset Management" },
  { tk: "BMY", name: "Bristol Myers Squibb", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "BNY", name: "Bank of New York Mellon Corp", sector: "Financial Services", industry: "Asset Management" },
  { tk: "BR", name: "Broadridge Financial Solutions", sector: "Technology", industry: "Information Technology Services" },
  { tk: "BRK-B", name: "Berkshire Hathaway", sector: "Financial Services", industry: "Insurance - Diversified" },
  { tk: "BRO", name: "Brown & Brown", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "BSX", name: "Boston Scientific", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "BX", name: "Blackstone Inc.", sector: "Financial Services", industry: "Asset Management" },
  { tk: "BXP", name: "BXP, Inc.", sector: "Real Estate", industry: "REIT - Office" },
  { tk: "C", name: "Citigroup", sector: "Financial Services", industry: "Banks - Diversified" },
  { tk: "CAH", name: "Cardinal Health", sector: "Healthcare", industry: "Medical - Distribution" },
  { tk: "CARR", name: "Carrier Global", sector: "Industrials", industry: "Construction" },
  { tk: "CASY", name: "Casey's General Stores, Inc.", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "CAT", name: "Caterpillar Inc.", sector: "Industrials", industry: "Agricultural - Machinery" },
  { tk: "CB", name: "Chubb Limited", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "CBOE", name: "Cboe Global Markets", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "CBRE", name: "CBRE Group", sector: "Real Estate", industry: "Real Estate - Services" },
  { tk: "CCI", name: "Crown Castle", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "CCL", name: "Carnival", sector: "Consumer Cyclical", industry: "Leisure" },
  { tk: "CDNS", name: "Cadence Design Systems", sector: "Technology", industry: "Software - Application" },
  { tk: "CDW", name: "CDW", sector: "Technology", industry: "Information Technology Services" },
  { tk: "CEG", name: "Constellation Energy", sector: "Utilities", industry: "Renewable Utilities" },
  { tk: "CF", name: "CF Industries", sector: "Basic Materials", industry: "Agricultural Inputs" },
  { tk: "CFG", name: "Citizens Financial Group", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "CHD", name: "Church & Dwight", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "CHRW", name: "C.H. Robinson", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "CHTR", name: "Charter Communications", sector: "Communication Services", industry: "Telecommunications Services" },
  { tk: "CI", name: "Cigna", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "CIEN", name: "Ciena Corporation", sector: "Technology", industry: "Communication Equipment" },
  { tk: "CINF", name: "Cincinnati Financial", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "CL", name: "Colgate-Palmolive", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "CLX", name: "Clorox", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "CMCSA", name: "Comcast", sector: "Communication Services", industry: "Telecommunications Services" },
  { tk: "CME", name: "CME Group", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "CMI", name: "Cummins", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "CMS", name: "CMS Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "CNC", name: "Centene Corporation", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "CNP", name: "CenterPoint Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "COF", name: "Capital One", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "COHR", name: "Coherent, Inc.", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "COIN", name: "Coinbase Global", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "COO", name: "Cooper Companies (The)", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "COP", name: "ConocoPhillips", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "COR", name: "Cencora", sector: "Healthcare", industry: "Medical - Distribution" },
  { tk: "COST", name: "Costco", sector: "Consumer Defensive", industry: "Discount Stores" },
  { tk: "CPAY", name: "Corpay", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "CPRT", name: "Copart", sector: "Consumer Cyclical", industry: "Auto - Dealerships" },
  { tk: "CPT", name: "Camden Property Trust", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "CRH", name: "CRH plc", sector: "Basic Materials", industry: "Construction Materials" },
  { tk: "CRL", name: "Charles River Laboratories", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "CRM", name: "Salesforce", sector: "Technology", industry: "Software - Application" },
  { tk: "CRWD", name: "CrowdStrike", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "CSCO", name: "Cisco", sector: "Technology", industry: "Communication Equipment" },
  { tk: "CSGP", name: "CoStar Group", sector: "Real Estate", industry: "Real Estate - Services" },
  { tk: "CSX", name: "CSX Corporation", sector: "Industrials", industry: "Railroads" },
  { tk: "CTAS", name: "Cintas", sector: "Industrials", industry: "Specialty Business Services" },
  { tk: "CTSH", name: "Cognizant", sector: "Technology", industry: "Information Technology Services" },
  { tk: "CTVA", name: "Corteva", sector: "Basic Materials", industry: "Agricultural Inputs" },
  { tk: "CVNA", name: "Carvana Co.", sector: "Consumer Cyclical", industry: "Auto - Dealerships" },
  { tk: "CVS", name: "CVS Health", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "CVX", name: "Chevron Corporation", sector: "Energy", industry: "Oil & Gas Integrated" },
  { tk: "D", name: "Dominion Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "DAL", name: "Delta Air Lines", sector: "Industrials", industry: "Airlines, Airports & Air Services" },
  { tk: "DASH", name: "DoorDash", sector: "Communication Services", industry: "Internet Content & Information" },
  { tk: "DD", name: "DuPont", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "DDOG", name: "Datadog", sector: "Technology", industry: "Software - Application" },
  { tk: "DE", name: "Deere & Company", sector: "Industrials", industry: "Agricultural - Machinery" },
  { tk: "DECK", name: "Deckers Brands", sector: "Consumer Cyclical", industry: "Apparel - Footwear & Accessories" },
  { tk: "DELL", name: "Dell Technologies", sector: "Technology", industry: "Computer Hardware" },
  { tk: "DG", name: "Dollar General", sector: "Consumer Defensive", industry: "Discount Stores" },
  { tk: "DGX", name: "Quest Diagnostics", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "DHI", name: "D. R. Horton", sector: "Consumer Cyclical", industry: "Residential Construction" },
  { tk: "DHR", name: "Danaher Corporation", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "DIS", name: "Walt Disney Company (The)", sector: "Communication Services", industry: "Entertainment" },
  { tk: "DLR", name: "Digital Realty", sector: "Real Estate", industry: "REIT - Office" },
  { tk: "DLTR", name: "Dollar Tree", sector: "Consumer Defensive", industry: "Discount Stores" },
  { tk: "DOC", name: "Healthpeak Properties", sector: "Real Estate", industry: "REIT - Healthcare Facilities" },
  { tk: "DOV", name: "Dover Corporation", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "DOW", name: "Dow Inc.", sector: "Basic Materials", industry: "Chemicals" },
  { tk: "DPZ", name: "Domino's", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "DRI", name: "Darden Restaurants", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "DTE", name: "DTE Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "DUK", name: "Duke Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "DVA", name: "DaVita", sector: "Healthcare", industry: "Medical - Care Facilities" },
  { tk: "DVN", name: "Devon Energy", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "DXCM", name: "Dexcom", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "EA", name: "Electronic Arts", sector: "Technology", industry: "Electronic Gaming & Multimedia" },
  { tk: "EBAY", name: "eBay", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "ECL", name: "Ecolab", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "ED", name: "Consolidated Edison", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "EFX", name: "Equifax", sector: "Industrials", industry: "Consulting Services" },
  { tk: "EG", name: "Everest Group", sector: "Financial Services", industry: "Insurance - Reinsurance" },
  { tk: "EIX", name: "Edison International", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "EL", name: "Estée Lauder Companies (The)", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "ELV", name: "Elevance Health", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "EME", name: "EMCOR Group, Inc.", sector: "Industrials", industry: "Engineering & Construction" },
  { tk: "EMR", name: "Emerson Electric", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "EOG", name: "EOG Resources", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "EQIX", name: "Equinix", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "EQR", name: "Equity Residential", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "EQT", name: "EQT Corporation", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "ERIE", name: "Erie Indemnity", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "ES", name: "Eversource Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "ESS", name: "Essex Property Trust", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "ETN", name: "Eaton Corporation", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "ETR", name: "Entergy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "EVRG", name: "Evergy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "EW", name: "Edwards Lifesciences", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "EXC", name: "Exelon", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "EXE", name: "Expand Energy", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "EXPD", name: "Expeditors International", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "EXPE", name: "Expedia Group", sector: "Consumer Cyclical", industry: "Travel Services" },
  { tk: "EXR", name: "Extra Space Storage", sector: "Real Estate", industry: "REIT - Industrial" },
  { tk: "F", name: "Ford Motor Company", sector: "Consumer Cyclical", industry: "Auto - Manufacturers" },
  { tk: "FANG", name: "Diamondback Energy", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "FAST", name: "Fastenal", sector: "Industrials", industry: "Industrial - Distribution" },
  { tk: "FCX", name: "Freeport-McMoRan", sector: "Basic Materials", industry: "Copper" },
  { tk: "FDS", name: "FactSet", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "FDX", name: "FedEx", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "FDXF", name: "FedEx Freight Holding Company, Inc.", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "FE", name: "FirstEnergy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "FFIV", name: "F5, Inc.", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "FICO", name: "Fair Isaac", sector: "Technology", industry: "Software - Application" },
  { tk: "FIS", name: "Fidelity National Information Services", sector: "Technology", industry: "Information Technology Services" },
  { tk: "FISV", name: "Fiserv, Inc.", sector: "Technology", industry: "Information Technology Services" },
  { tk: "FITB", name: "Fifth Third Bancorp", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "FIX", name: "Comfort Systems USA, Inc.", sector: "Industrials", industry: "Engineering & Construction" },
  { tk: "FLEX", name: "Flex Ltd.", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "FOX", name: "Fox Corporation (Class B)", sector: "Communication Services", industry: "Entertainment" },
  { tk: "FOXA", name: "Fox Corporation (Class A)", sector: "Communication Services", industry: "Entertainment" },
  { tk: "FRT", name: "Federal Realty Investment Trust", sector: "Real Estate", industry: "REIT - Retail" },
  { tk: "FSLR", name: "First Solar", sector: "Energy", industry: "Solar" },
  { tk: "FTNT", name: "Fortinet", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "FTV", name: "Fortive", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "GD", name: "General Dynamics", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "GDDY", name: "GoDaddy", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "GE", name: "GE Aerospace", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "GEHC", name: "GE HealthCare", sector: "Healthcare", industry: "Medical - Healthcare Information Services" },
  { tk: "GEN", name: "Gen Digital", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "GEV", name: "GE Vernova", sector: "Utilities", industry: "Renewable Utilities" },
  { tk: "GILD", name: "Gilead Sciences", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "GIS", name: "General Mills", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { tk: "GL", name: "Globe Life", sector: "Financial Services", industry: "Insurance - Life" },
  { tk: "GLW", name: "Corning Inc.", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "GM", name: "General Motors", sector: "Consumer Cyclical", industry: "Auto - Manufacturers" },
  { tk: "GNRC", name: "Generac", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "GOOG", name: "Alphabet Inc. (Class C)", sector: "Communication Services", industry: "Internet Content & Information" },
  { tk: "GOOGL", name: "Alphabet Inc. (Class A)", sector: "Communication Services", industry: "Internet Content & Information" },
  { tk: "GPC", name: "Genuine Parts Company", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "GPN", name: "Global Payments", sector: "Industrials", industry: "Specialty Business Services" },
  { tk: "GRMN", name: "Garmin", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "GS", name: "Goldman Sachs", sector: "Financial Services", industry: "Financial - Capital Markets" },
  { tk: "GWW", name: "W. W. Grainger", sector: "Industrials", industry: "Industrial - Distribution" },
  { tk: "HAL", name: "Halliburton", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { tk: "HAS", name: "Hasbro", sector: "Consumer Cyclical", industry: "Leisure" },
  { tk: "HBAN", name: "Huntington Bancshares", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "HCA", name: "HCA Healthcare", sector: "Healthcare", industry: "Medical - Care Facilities" },
  { tk: "HD", name: "Home Depot (The)", sector: "Consumer Cyclical", industry: "Home Improvement" },
  { tk: "HIG", name: "Hartford (The)", sector: "Financial Services", industry: "Insurance - Diversified" },
  { tk: "HII", name: "Huntington Ingalls Industries", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "HLT", name: "Hilton Worldwide", sector: "Consumer Cyclical", industry: "Travel Lodging" },
  { tk: "HON", name: "Honeywell", sector: "Industrials", industry: "Conglomerates" },
  { tk: "HONA", name: "Honeywell Aerospace Inc", sector: "Technology", industry: "Aerospace & Defense" },
  { tk: "HOOD", name: "Robinhood Markets, Inc.", sector: "Financial Services", industry: "Financial - Capital Markets" },
  { tk: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", industry: "Communication Equipment" },
  { tk: "HPQ", name: "HP Inc.", sector: "Technology", industry: "Computer Hardware" },
  { tk: "HRL", name: "Hormel Foods", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { tk: "HSIC", name: "Henry Schein", sector: "Healthcare", industry: "Medical - Distribution" },
  { tk: "HST", name: "Host Hotels & Resorts", sector: "Real Estate", industry: "REIT - Hotel & Motel" },
  { tk: "HSY", name: "Hershey Company (The)", sector: "Consumer Defensive", industry: "Food Confectioners" },
  { tk: "HUBB", name: "Hubbell Incorporated", sector: "Industrials", industry: "Electrical Equipment & Parts" },
  { tk: "HUM", name: "Humana", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "HWM", name: "Howmet Aerospace", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "IBKR", name: "Interactive Brokers Group", sector: "Financial Services", industry: "Investment - Banking & Investment Services" },
  { tk: "IBM", name: "IBM", sector: "Technology", industry: "Information Technology Services" },
  { tk: "ICE", name: "Intercontinental Exchange", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "IDXX", name: "Idexx Laboratories", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "IEX", name: "IDEX Corporation", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "IFF", name: "International Flavors & Fragrances", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "INCY", name: "Incyte", sector: "Healthcare", industry: "Biotechnology" },
  { tk: "INTC", name: "Intel", sector: "Technology", industry: "Semiconductors" },
  { tk: "INTU", name: "Intuit", sector: "Technology", industry: "Software - Application" },
  { tk: "INVH", name: "Invitation Homes", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "IP", name: "International Paper", sector: "Consumer Cyclical", industry: "Packaging & Containers" },
  { tk: "IQV", name: "IQVIA", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "IR", name: "Ingersoll Rand", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "IRM", name: "Iron Mountain", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "IT", name: "Gartner", sector: "Technology", industry: "Information Technology Services" },
  { tk: "ITW", name: "Illinois Tool Works", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "IVZ", name: "Invesco", sector: "Financial Services", industry: "Asset Management" },
  { tk: "J", name: "Jacobs Solutions", sector: "Industrials", industry: "Engineering & Construction" },
  { tk: "JBHT", name: "J.B. Hunt", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "JBL", name: "Jabil", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "JCI", name: "Johnson Controls", sector: "Industrials", industry: "Construction" },
  { tk: "JKHY", name: "Jack Henry & Associates", sector: "Technology", industry: "Information Technology Services" },
  { tk: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "JPM", name: "JPMorgan Chase", sector: "Financial Services", industry: "Banks - Diversified" },
  { tk: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic" },
  { tk: "KEY", name: "KeyCorp", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "KEYS", name: "Keysight Technologies", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "KHC", name: "Kraft Heinz", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { tk: "KIM", name: "Kimco Realty", sector: "Real Estate", industry: "REIT - Retail" },
  { tk: "KKR", name: "KKR", sector: "Financial Services", industry: "Asset Management" },
  { tk: "KLAC", name: "KLA Corporation", sector: "Technology", industry: "Semiconductors" },
  { tk: "KMB", name: "Kimberly-Clark", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "KMI", name: "Kinder Morgan", sector: "Energy", industry: "Oil & Gas Midstream" },
  { tk: "KO", name: "Coca-Cola Company (The)", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic" },
  { tk: "KR", name: "Kroger", sector: "Consumer Defensive", industry: "Grocery Stores" },
  { tk: "KVUE", name: "Kenvue", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "L", name: "Loews Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "LDOS", name: "Leidos", sector: "Technology", industry: "Information Technology Services" },
  { tk: "LEN", name: "Lennar", sector: "Consumer Cyclical", industry: "Residential Construction" },
  { tk: "LH", name: "LabCorp", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "LHX", name: "L3Harris", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "LII", name: "Lennox International", sector: "Industrials", industry: "Construction" },
  { tk: "LIN", name: "Linde plc", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "LITE", name: "Lumentum Holdings Inc.", sector: "Technology", industry: "Communication Equipment" },
  { tk: "LLY", name: "Lilly (Eli)", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "LMT", name: "Lockheed Martin", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "LNT", name: "Alliant Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "LOW", name: "Lowe's", sector: "Consumer Cyclical", industry: "Home Improvement" },
  { tk: "LRCX", name: "Lam Research", sector: "Technology", industry: "Semiconductors" },
  { tk: "LULU", name: "Lululemon Athletica", sector: "Consumer Cyclical", industry: "Apparel - Retail" },
  { tk: "LUV", name: "Southwest Airlines", sector: "Industrials", industry: "Airlines, Airports & Air Services" },
  { tk: "LVS", name: "Las Vegas Sands", sector: "Consumer Cyclical", industry: "Gambling, Resorts & Casinos" },
  { tk: "LYB", name: "LyondellBasell", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "LYV", name: "Live Nation Entertainment", sector: "Communication Services", industry: "Entertainment" },
  { tk: "MA", name: "Mastercard", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "MAA", name: "Mid-America Apartment Communities", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "MAR", name: "Marriott International", sector: "Consumer Cyclical", industry: "Travel Lodging" },
  { tk: "MAS", name: "Masco", sector: "Industrials", industry: "Construction" },
  { tk: "MCD", name: "McDonald's", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "MCHP", name: "Microchip Technology", sector: "Technology", industry: "Semiconductors" },
  { tk: "MCK", name: "McKesson Corporation", sector: "Healthcare", industry: "Medical - Distribution" },
  { tk: "MCO", name: "Moody's Corporation", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "MDLZ", name: "Mondelez International", sector: "Consumer Defensive", industry: "Food Confectioners" },
  { tk: "MDT", name: "Medtronic", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "MET", name: "MetLife", sector: "Financial Services", industry: "Insurance - Life" },
  { tk: "META", name: "Meta Platforms", sector: "Communication Services", industry: "Internet Content & Information" },
  { tk: "MGM", name: "MGM Resorts", sector: "Consumer Cyclical", industry: "Gambling, Resorts & Casinos" },
  { tk: "MKC", name: "McCormick & Company", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { tk: "MLM", name: "Martin Marietta Materials", sector: "Basic Materials", industry: "Construction Materials" },
  { tk: "MMM", name: "3M", sector: "Industrials", industry: "Conglomerates" },
  { tk: "MNST", name: "Monster Beverage", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic" },
  { tk: "MO", name: "Altria", sector: "Consumer Defensive", industry: "Tobacco" },
  { tk: "MOS", name: "Mosaic Company (The)", sector: "Basic Materials", industry: "Agricultural Inputs" },
  { tk: "MPC", name: "Marathon Petroleum", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { tk: "MPWR", name: "Monolithic Power Systems", sector: "Technology", industry: "Semiconductors" },
  { tk: "MRK", name: "Merck & Co.", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "MRNA", name: "Moderna", sector: "Healthcare", industry: "Biotechnology" },
  { tk: "MRSH", name: "Marsh & McLennan Companies, Inc.", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "MRVL", name: "Marvell Technology, Inc.", sector: "Technology", industry: "Semiconductors" },
  { tk: "MS", name: "Morgan Stanley", sector: "Financial Services", industry: "Financial - Capital Markets" },
  { tk: "MSCI", name: "MSCI", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "MSFT", name: "Microsoft", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "MSI", name: "Motorola Solutions", sector: "Technology", industry: "Communication Equipment" },
  { tk: "MTB", name: "M&T Bank", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "MTD", name: "Mettler Toledo", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "MU", name: "Micron Technology", sector: "Technology", industry: "Semiconductors" },
  { tk: "NCLH", name: "Norwegian Cruise Line Holdings", sector: "Consumer Cyclical", industry: "Travel Services" },
  { tk: "NDAQ", name: "Nasdaq, Inc.", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "NDSN", name: "Nordson Corporation", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "NEE", name: "NextEra Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "NEM", name: "Newmont", sector: "Basic Materials", industry: "Gold" },
  { tk: "NFLX", name: "Netflix", sector: "Communication Services", industry: "Entertainment" },
  { tk: "NI", name: "NiSource", sector: "Utilities", industry: "Regulated Gas" },
  { tk: "NKE", name: "Nike, Inc.", sector: "Consumer Cyclical", industry: "Apparel - Footwear & Accessories" },
  { tk: "NOC", name: "Northrop Grumman", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "NOW", name: "ServiceNow", sector: "Technology", industry: "Software - Application" },
  { tk: "NRG", name: "NRG Energy", sector: "Utilities", industry: "Independent Power Producers" },
  { tk: "NSC", name: "Norfolk Southern Railway", sector: "Industrials", industry: "Railroads" },
  { tk: "NTAP", name: "NetApp", sector: "Technology", industry: "Computer Hardware" },
  { tk: "NTRS", name: "Northern Trust", sector: "Financial Services", industry: "Asset Management" },
  { tk: "NUE", name: "Nucor", sector: "Basic Materials", industry: "Steel" },
  { tk: "NVDA", name: "Nvidia", sector: "Technology", industry: "Semiconductors" },
  { tk: "NVR", name: "NVR, Inc.", sector: "Consumer Cyclical", industry: "Residential Construction" },
  { tk: "NWS", name: "News Corp (Class B)", sector: "Communication Services", industry: "Entertainment" },
  { tk: "NWSA", name: "News Corp (Class A)", sector: "Communication Services", industry: "Entertainment" },
  { tk: "NXPI", name: "NXP Semiconductors", sector: "Technology", industry: "Semiconductors" },
  { tk: "O", name: "Realty Income", sector: "Real Estate", industry: "REIT - Retail" },
  { tk: "ODFL", name: "Old Dominion", sector: "Industrials", industry: "Trucking" },
  { tk: "OKE", name: "ONEOK", sector: "Energy", industry: "Oil & Gas Midstream" },
  { tk: "OMC", name: "Omnicom Group", sector: "Communication Services", industry: "Advertising Agencies" },
  { tk: "ON", name: "ON Semiconductor", sector: "Technology", industry: "Semiconductors" },
  { tk: "ORCL", name: "Oracle Corporation", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "ORLY", name: "O'Reilly Auto Parts", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "OTIS", name: "Otis Worldwide", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "OXY", name: "Occidental Petroleum", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "PANW", name: "Palo Alto Networks", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "PAYX", name: "Paychex", sector: "Industrials", industry: "Staffing & Employment Services" },
  { tk: "PCAR", name: "Paccar", sector: "Industrials", industry: "Agricultural - Machinery" },
  { tk: "PCG", name: "PG&E Corporation", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "PEG", name: "Public Service Enterprise Group", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "PEP", name: "PepsiCo", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic" },
  { tk: "PFE", name: "Pfizer", sector: "Healthcare", industry: "Drug Manufacturers - General" },
  { tk: "PFG", name: "Principal Financial Group", sector: "Financial Services", industry: "Insurance - Diversified" },
  { tk: "PG", name: "Procter & Gamble", sector: "Consumer Defensive", industry: "Household & Personal Products" },
  { tk: "PGR", name: "Progressive Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "PH", name: "Parker Hannifin", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "PHM", name: "PulteGroup", sector: "Consumer Cyclical", industry: "Residential Construction" },
  { tk: "PKG", name: "Packaging Corporation of America", sector: "Consumer Cyclical", industry: "Packaging & Containers" },
  { tk: "PLD", name: "Prologis", sector: "Real Estate", industry: "REIT - Industrial" },
  { tk: "PLTR", name: "Palantir Technologies", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "PM", name: "Philip Morris International", sector: "Consumer Defensive", industry: "Tobacco" },
  { tk: "PNC", name: "PNC Financial Services", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "PNR", name: "Pentair", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "PNW", name: "Pinnacle West", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "PODD", name: "Insulet Corporation", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "PPG", name: "PPG Industries", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "PPL", name: "PPL Corporation", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "PRU", name: "Prudential Financial", sector: "Financial Services", industry: "Insurance - Life" },
  { tk: "PSA", name: "Public Storage", sector: "Real Estate", industry: "REIT - Industrial" },
  { tk: "PSKY", name: "Paramount Skydance Corp", sector: "Communication Services", industry: "Entertainment" },
  { tk: "PSX", name: "Phillips 66", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { tk: "PTC", name: "PTC Inc.", sector: "Technology", industry: "Software - Application" },
  { tk: "PWR", name: "Quanta Services", sector: "Industrials", industry: "Engineering & Construction" },
  { tk: "PYPL", name: "PayPal", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "Q", name: "Qnity Electronics, Inc.", sector: "Technology", industry: "Semiconductors" },
  { tk: "QCOM", name: "Qualcomm", sector: "Technology", industry: "Semiconductors" },
  { tk: "RCL", name: "Royal Caribbean Group", sector: "Consumer Cyclical", industry: "Travel Services" },
  { tk: "REG", name: "Regency Centers", sector: "Real Estate", industry: "REIT - Retail" },
  { tk: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", industry: "Biotechnology" },
  { tk: "RF", name: "Regions Financial Corporation", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "RJF", name: "Raymond James Financial", sector: "Financial Services", industry: "Financial - Capital Markets" },
  { tk: "RL", name: "Ralph Lauren Corporation", sector: "Consumer Cyclical", industry: "Apparel - Manufacturers" },
  { tk: "RMD", name: "ResMed", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "ROK", name: "Rockwell Automation", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "ROL", name: "Rollins, Inc.", sector: "Consumer Cyclical", industry: "Personal Products & Services" },
  { tk: "ROP", name: "Roper Technologies", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "ROST", name: "Ross Stores", sector: "Consumer Cyclical", industry: "Apparel - Retail" },
  { tk: "RSG", name: "Republic Services", sector: "Industrials", industry: "Waste Management" },
  { tk: "RTX", name: "RTX Corporation", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "RVTY", name: "Revvity", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "SATS", name: "EchoStar Corporation", sector: "Technology", industry: "Communication Equipment" },
  { tk: "SBAC", name: "SBA Communications", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "SBUX", name: "Starbucks", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "SCHW", name: "Charles Schwab Corporation", sector: "Financial Services", industry: "Financial - Capital Markets" },
  { tk: "SHW", name: "Sherwin-Williams", sector: "Basic Materials", industry: "Chemicals - Specialty" },
  { tk: "SJM", name: "J.M. Smucker Company (The)", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { tk: "SLB", name: "Schlumberger", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { tk: "SMCI", name: "Supermicro", sector: "Technology", industry: "Computer Hardware" },
  { tk: "SNA", name: "Snap-on", sector: "Industrials", industry: "Manufacturing - Tools & Accessories" },
  { tk: "SNDK", name: "Sandisk Corporation", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "SNPS", name: "Synopsys", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "SO", name: "Southern Company", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "SOLV", name: "Solventum", sector: "Healthcare", industry: "Medical - Care Facilities" },
  { tk: "SPG", name: "Simon Property Group", sector: "Real Estate", industry: "REIT - Retail" },
  { tk: "SPGI", name: "S&P Global", sector: "Financial Services", industry: "Financial - Data & Stock Exchanges" },
  { tk: "SRE", name: "Sempra", sector: "Utilities", industry: "Diversified Utilities" },
  { tk: "STE", name: "Steris", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "STLD", name: "Steel Dynamics", sector: "Basic Materials", industry: "Steel" },
  { tk: "STT", name: "State Street Corporation", sector: "Financial Services", industry: "Asset Management" },
  { tk: "STX", name: "Seagate Technology", sector: "Technology", industry: "Computer Hardware" },
  { tk: "STZ", name: "Constellation Brands", sector: "Consumer Defensive", industry: "Beverages - Wineries & Distilleries" },
  { tk: "SW", name: "Smurfit WestRock", sector: "Consumer Cyclical", industry: "Packaging & Containers" },
  { tk: "SWK", name: "Stanley Black & Decker", sector: "Industrials", industry: "Manufacturing - Tools & Accessories" },
  { tk: "SWKS", name: "Skyworks Solutions", sector: "Technology", industry: "Semiconductors" },
  { tk: "SYF", name: "Synchrony Financial", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "SYK", name: "Stryker Corporation", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "SYY", name: "Sysco", sector: "Consumer Defensive", industry: "Food Distribution" },
  { tk: "T", name: "AT&T", sector: "Communication Services", industry: "Telecommunications Services" },
  { tk: "TAP", name: "Molson Coors Beverage Company", sector: "Consumer Defensive", industry: "Beverages - Alcoholic" },
  { tk: "TDG", name: "TransDigm Group", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "TDY", name: "Teledyne Technologies", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "TECH", name: "Bio-Techne", sector: "Healthcare", industry: "Biotechnology" },
  { tk: "TEL", name: "TE Connectivity", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "TER", name: "Teradyne", sector: "Technology", industry: "Semiconductors" },
  { tk: "TFC", name: "Truist Financial", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "TGT", name: "Target Corporation", sector: "Consumer Defensive", industry: "Discount Stores" },
  { tk: "TJX", name: "TJX Companies", sector: "Consumer Cyclical", industry: "Apparel - Retail" },
  { tk: "TKO", name: "TKO Group Holdings", sector: "Communication Services", industry: "Entertainment" },
  { tk: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "TMUS", name: "T-Mobile US", sector: "Communication Services", industry: "Telecommunications Services" },
  { tk: "TPL", name: "Texas Pacific Land Corporation", sector: "Energy", industry: "Oil & Gas Exploration & Production" },
  { tk: "TPR", name: "Tapestry, Inc.", sector: "Consumer Cyclical", industry: "Luxury Goods" },
  { tk: "TRGP", name: "Targa Resources", sector: "Energy", industry: "Oil & Gas Midstream" },
  { tk: "TRMB", name: "Trimble Inc.", sector: "Technology", industry: "Hardware, Equipment & Parts" },
  { tk: "TROW", name: "T. Rowe Price", sector: "Financial Services", industry: "Asset Management" },
  { tk: "TRV", name: "Travelers Companies (The)", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "TSCO", name: "Tractor Supply", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "TSLA", name: "Tesla, Inc.", sector: "Consumer Cyclical", industry: "Auto - Manufacturers" },
  { tk: "TSN", name: "Tyson Foods", sector: "Consumer Defensive", industry: "Agricultural Farm Products" },
  { tk: "TT", name: "Trane Technologies", sector: "Industrials", industry: "Construction" },
  { tk: "TTD", name: "The Trade Desk, Inc.", sector: "Technology", industry: "Software - Application" },
  { tk: "TTWO", name: "Take-Two Interactive", sector: "Technology", industry: "Electronic Gaming & Multimedia" },
  { tk: "TXN", name: "Texas Instruments", sector: "Technology", industry: "Semiconductors" },
  { tk: "TXT", name: "Textron", sector: "Industrials", industry: "Aerospace & Defense" },
  { tk: "TYL", name: "Tyler Technologies", sector: "Technology", industry: "Software - Application" },
  { tk: "UAL", name: "United Airlines Holdings", sector: "Industrials", industry: "Airlines, Airports & Air Services" },
  { tk: "UBER", name: "Uber", sector: "Technology", industry: "Software - Application" },
  { tk: "UDR", name: "UDR, Inc.", sector: "Real Estate", industry: "REIT - Residential" },
  { tk: "UHS", name: "Universal Health Services", sector: "Healthcare", industry: "Medical - Care Facilities" },
  { tk: "ULTA", name: "Ulta Beauty", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "UNH", name: "UnitedHealth Group", sector: "Healthcare", industry: "Medical - Healthcare Plans" },
  { tk: "UNP", name: "Union Pacific Corporation", sector: "Industrials", industry: "Railroads" },
  { tk: "UPS", name: "United Parcel Service", sector: "Industrials", industry: "Integrated Freight & Logistics" },
  { tk: "URI", name: "United Rentals", sector: "Industrials", industry: "Rental & Leasing Services" },
  { tk: "USB", name: "U.S. Bancorp", sector: "Financial Services", industry: "Banks - Regional" },
  { tk: "V", name: "Visa Inc.", sector: "Financial Services", industry: "Financial - Credit Services" },
  { tk: "VEEV", name: "Veeva Systems Inc.", sector: "Healthcare", industry: "Medical - Healthcare Information Services" },
  { tk: "VICI", name: "Vici Properties", sector: "Real Estate", industry: "REIT - Diversified" },
  { tk: "VLO", name: "Valero Energy", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { tk: "VLTO", name: "Veralto", sector: "Industrials", industry: "Industrial - Pollution & Treatment Controls" },
  { tk: "VMC", name: "Vulcan Materials Company", sector: "Basic Materials", industry: "Construction Materials" },
  { tk: "VRSK", name: "Verisk Analytics", sector: "Industrials", industry: "Consulting Services" },
  { tk: "VRSN", name: "Verisign", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "VRT", name: "Vertiv Holdings Co", sector: "Industrials", industry: "Electrical Equipment & Parts" },
  { tk: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", industry: "Biotechnology" },
  { tk: "VST", name: "Vistra Corp.", sector: "Utilities", industry: "Independent Power Producers" },
  { tk: "VTR", name: "Ventas", sector: "Real Estate", industry: "REIT - Healthcare Facilities" },
  { tk: "VTRS", name: "Viatris", sector: "Healthcare", industry: "Drug Manufacturers - Specialty & Generic" },
  { tk: "VZ", name: "Verizon", sector: "Communication Services", industry: "Telecommunications Services" },
  { tk: "WAB", name: "Wabtec", sector: "Industrials", industry: "Railroads" },
  { tk: "WAT", name: "Waters Corporation", sector: "Healthcare", industry: "Medical - Diagnostics & Research" },
  { tk: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services", industry: "Entertainment" },
  { tk: "WDAY", name: "Workday, Inc.", sector: "Technology", industry: "Software - Application" },
  { tk: "WDC", name: "Western Digital", sector: "Technology", industry: "Computer Hardware" },
  { tk: "WEC", name: "WEC Energy Group", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "WELL", name: "Welltower", sector: "Real Estate", industry: "REIT - Healthcare Facilities" },
  { tk: "WFC", name: "Wells Fargo", sector: "Financial Services", industry: "Banks - Diversified" },
  { tk: "WM", name: "Waste Management", sector: "Industrials", industry: "Waste Management" },
  { tk: "WMB", name: "Williams Companies", sector: "Energy", industry: "Oil & Gas Midstream" },
  { tk: "WMT", name: "Walmart", sector: "Consumer Defensive", industry: "Discount Stores" },
  { tk: "WRB", name: "W. R. Berkley Corporation", sector: "Financial Services", industry: "Insurance - Property & Casualty" },
  { tk: "WSM", name: "Williams-Sonoma", sector: "Consumer Cyclical", industry: "Specialty Retail" },
  { tk: "WST", name: "West Pharmaceutical Services", sector: "Healthcare", industry: "Medical - Instruments & Supplies" },
  { tk: "WTW", name: "Willis Towers Watson", sector: "Financial Services", industry: "Insurance - Brokers" },
  { tk: "WY", name: "Weyerhaeuser", sector: "Real Estate", industry: "REIT - Specialty" },
  { tk: "WYNN", name: "Wynn Resorts", sector: "Consumer Cyclical", industry: "Gambling, Resorts & Casinos" },
  { tk: "XEL", name: "Xcel Energy", sector: "Utilities", industry: "Regulated Electric" },
  { tk: "XOM", name: "ExxonMobil", sector: "Energy", industry: "Oil & Gas Integrated" },
  { tk: "XYL", name: "Xylem Inc.", sector: "Industrials", industry: "Industrial - Machinery" },
  { tk: "XYZ", name: "Block, Inc.", sector: "Technology", industry: "Software - Infrastructure" },
  { tk: "YUM", name: "Yum! Brands", sector: "Consumer Cyclical", industry: "Restaurants" },
  { tk: "ZBH", name: "Zimmer Biomet", sector: "Healthcare", industry: "Medical - Devices" },
  { tk: "ZBRA", name: "Zebra Technologies", sector: "Technology", industry: "Communication Equipment" },
  { tk: "ZTS", name: "Zoetis", sector: "Healthcare", industry: "Drug Manufacturers - Specialty & Generic" },
];
